name: 'Setup MicroShift OpenShift Cluster'
description: 'This action sets up an MicroShift OpenShift Cluster in your environment'
author: 'Marc Nuri'
branding:
  icon: circle
  color: red
inputs:
  github token:
    description: 'GITHUB_TOKEN to be able to perform requests to GH REST API (with no limit)'
runs:
  using: 'node20'
  main: 'src/index.js'
