name: Run action (E2E tests)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  default-inputs:
    name: Defaults
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Test Action
        uses: ./
        with:
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Cluster
        run: kubectl get nodes
